; Pack of smileys for use with IEView plugin.
; Smiles KOLOBOK-Style http://www.kolobok.us
; Design smiles & animated by Mantsurov Aiwan aiwan@yandex.ru
; Light skin CODE
Name    = "KOLOBOK For IEView. Original [Big Pack]"
Author  = "Aiwan (www.kolobok.us)"
Date    = "27.11.2007"
Version = "2.0 (For dark skin. Small)"
;
SelectionSize = 45, 35
WindowSize = 7, 7
;------------------------------------------
;            Icq CODE START
;------------------------------------------
Smiley = "angel.gif" , 0, "O:-) O:) O+) O=) 0:-) 0:) 0+) 0=) (A) (a)", "O:-)"
Smiley = "smile.gif" , 0, ":-) :) +) =) :smile:", ":-)"
Smiley = "sad.gif" , 0 ,":-( :( +( =( :-(( :(( +(( =(( :sad:", ":-("
Smiley = "wink.gif" , 0, ";-) ;) ^_~ :wink:", ";-)"
Smiley = "blum3.gif" , 0, ":-P :P :-p :p +P =P +p =p :-b :b +b =b :tongue:", ":-P"
Smiley = "dirol.gif", 0, "8-) 8) B) :COOL: :cool: COOL cool COOL! COOL!! COOL!!!", "8-)"
Smiley = "biggrin.gif", 0, ":-D :D +D =D :biggrin:", ":-D"
Smiley = "blush2.gif" , 0, ":-[ :[ ;'> ;-. :blush:", ":-["
Smiley = "shok.gif", 0, "=-O =O =-o =0 O_O O_o o_O O_0 o_0 0_O 0_o", "O_O"
Smiley = "kiss.gif" , 0, ":-* :* :-{} :{} +{} ={} ^.^ :kiss: *KISS*", ":-*"
Smiley = "cray.gif" , 0, ":'( :'-(", ":'("
Smiley = "secret.gif", 0, ":-X :-x X: x: :-# :# :secret:", ":-X"
Smiley = "aggressive.gif", 0, ">:o >:O >+O >:o >+o :-@ :angry:", ">:o"
Smiley = "fool.gif", 0, ":-| :| =|", ":-|"
Smiley = "beee.gif", 0, ":-\ :-/ :\", ":-\"
Smiley = "mosking.gif" , 0, "*JOKINGLY* 8P 8p", "*JOKINGLY*"
Smiley = "diablo.gif", 0, "]:-> }:-> ]:> }:> >:-] >:] (6) :diablo: *DIABLO*", "]:->"
Smiley = "music2.gif", 0, "[:-} [:}", "[:-}"
Smiley = "air_kiss.gif", 0, "*KISSED*", "*KISSED*"
Smiley = "bad.gif", 0, ":-! :! :-~ ;-~ :(~ +(~ =(~ :bad:", ":-!"
Smiley = "boredom.gif", 0, "*TIRED* |-0 :boredom:", "*TIRED*"
Smiley = "stop.gif", 0, "*STOP* STOP STOP! STOP!! STOP!!! :stop:", "*STOP*"
Smiley = "kiss_3.gif", 0, "*KISSING*", "*KISSING*"
Smiley = "give_rose.gif", 0, "@}->-- @}-:-- @>}--,-`--- (F) (f)", "@}->--"
Smiley = "good.gif", 0, "*THUMBS%%_%%UP* :GOOD: :good: GOOD! *GOOD*", "*THUMBS UP*"
Smiley = "drinks.gif", 0, "*DRINK* DRINK :drink:", "*DRINK*"
Smiley = "man_in_love.gif", 0, "*IN%%_%%LOVE* LOVE", "*IN LOVE*"
Smiley = "bomb.gif", 0, "@=", "@="
Smiley = "wacko.gif", 0, "%) %-) :-$ :$ :wacko: :WACKO:", "%)"
;------------------------------------------
;               Icq CODE End
;------------------------------------------
;             Custom CODE START
;------------------------------------------
Smiley = "mamba.gif", 0, "*WASSUP* *SUP* *MAMBA* :MAMBA:", "*WASSUP*"
Smiley = "clapping.gif", 0, "*BRAVO* :BRAVO: :bravo: :clapping:", "*BRAVO*"
Smiley = "ROFL.gif", 0, "*ROFL* :ROFL: :rofl: ROFL ROFL! rofl :-)))) :-))))) :-)))))) :)))) :))))) :)))))) =)))) =))))) =))))))", "*ROFL*"
Smiley = "pardon.gif", 0, "*PARDON* =] :PARDON: :pardon: PARDON pardon", "*PARDON*"
Smiley = "nea.gif", 0, "*NO*", "*NO*"
Smiley* = "lol.gif", 0, "*LOL* :-)) :)) =)) +)) :-))) :))) LOL lol LOL! lol! :lol:", "*LOL*"
Smiley = "crazy.gif", 0, "*CRAZY* :crazy:", "*CRAZY*"
Smiley = "dntknw.gif", 0, "*DONT_KNOW* *UNKNOWN* :HZ: :hz:", "*DONT_KNOW*"
Smiley = "sorry.gif", 0, "*SORRY* :sorry:", "*SORRY*"
Smiley = "yahoo.gif", 0, "*YAHOO* *YAHOO!* :YAHOO: :yahoo: YAHOO! Yahoo! YAHOO!! Yahoo!! YAHOO!!! Yahoo!!!", "*YAHOO*"
Smiley = "dance4.gif", 0, "*DANCE* :dance:", "*DANCE*"
Smiley* = "pleasantry.gif", 0, "*db* :db:", "*db*"
Smiley* = "i-m_so_happy.gif", 0, "*HAPPY* :happy: :HAPPY: :Happy: ^^", "*HAPPY*"
;------------------------------------------
;         Custom CODE for BIG PACK
;------------------------------------------
Smiley = "help.gif", 0, "*HELP*", "*HELP*"
Smiley = "new_russian.gif", 0, "\m/", "\m/"
Smiley = "ok.gif", 0, "*OK*", "*OK*"
Smiley* = "acute.gif", 0, ";D *ACUTE*", "*ACUTE*"
Smiley* = "bb.gif", 0, "*BB*", "*BB*"
Smiley* = "bye.gif", 0, "*BYE*", "*BYE*"
Smiley* = "hi.gif", 0, "*HI*", "*HI*"
Smiley* = "scratch_one-s_head.gif", 0, "*SCRATCH*", "*SCRATCH*"
Smiley* = "yes2.gif", 0, "*YEEES!* *YES!*", "*YES!*"
Smiley* = "smoke.gif", 0, "*SMOKE*", "*SMOKE*"
Smiley* = "big_boss.gif", 0, "*BOSS*", "*BOSS*"
Smiley* = "sarcastic.gif", 0, "*SARCASTIC*", "*SARCASTIC*"
Smiley* = "boast.gif", 0, "*BOAST*", "*BOAST*"
Smiley* = "prankster2.gif", 0, "*HOHO*", "*HOHO*"
Smiley* = "shout.gif", 0, "*SHOUT*", "*SHOUT*"
Smiley* = "black_eye.gif", 0, "*VAVA*", "*VAVA*"
Smiley* = "censored.gif", 0, "*CENSORED*", "*CENSORED*"
Smiley* = "search.gif", 0, "*SEARCH*", "*SEARCH*"
Smiley* = "beach.gif", 0, "*BEACH*", "*BEACH*"
Smiley* = "focus.gif", 0, "*FOCUS*", "*FOCUS*"
Smiley* = "hunter.gif", 0, "*HUNTER*", "*HUNTER*"
Smiley* = "girl_cray2.gif", 0, "*GIRL_CRY* *GIRL_CRAY*", "*GIRL_CRY*"
Smiley* = "girl_crazy.gif", 0, "*GIRL_CRAZY*", "*GIRL_CRAZY*"
Smiley* = "girl_hospital.gif", 0, "*HOSPITAL*", "*HOSPITAL*"
Smiley* = "girl_in_love.gif", 0, "*GIRL_IN_LOVE*", "*GIRL_IN_LOVE*"
Smiley* = "girl_pinkglassesf.gif", 0, "*PINKGLASSES*", "*PINKGLASSES*"
Smiley* = "hysteric.gif", 0, "*HYSTERIC*", "*HYSTERIC*"
Smiley* = "tender.gif", 0, "*TENDER*", "*TENDER*"
Smiley* = "spruce_up.gif", 0, "*SPRUSE_UP*", "*SPRUSE_UP*"
Smiley* = "flirt.gif", 0, "*FLIRT*", "*FLIRT*"
Smiley* = "give_heart.gif", 0, "*GIVE_HEART*", "*GIVE_HEART*"
Smiley* = "curtsey.gif", 0, "*CURTSEY*", "*CURTSEY*"
Smiley* = "feminist.gif", 0, "*FEMINIST*", "*FEMINIST*"
Smiley* = "girl_drink1.gif", 0, "*GIRL_DRINK*", "*GIRL_DRINK*"
Smiley* = "girl_haha.gif", 0, "*HAHA*", "*HAHA*"
Smiley* = "girl_impossible.gif", 0, "*IMPOSSIBLE*", "*IMPOSSIBLE*"
Smiley* = "girl_sigh.gif", 0, "*SIGH*", "*SIGH*"
Smiley* = "hang2.gif", 0, "X-) X)", "X-)"
Smiley* = "slow.gif", 0, "*SLOW*", "*SLOW*"
Smiley* = "moil.gif", 0, "*MOIL* *JOB*", "*MOIL*"
Smiley* = "yes3.gif", 0, "*YES*", "*YES*"
Smiley* = "swoon2.gif", 0, "*MEGA_SHOK*", "*MEGA_SHOK*"
Smiley* = "thank_you.gif", 0, "*THANK*", "*THANK*"
Smiley* = "king.gif", 0, "*KING*", "*KING*"
Smiley* = "lazy.gif", 0, "*LAZY*", "*LAZY*"
Smiley* = "friends.gif", 0, "*FRIEND*", "*FRIEND*"
Smiley* = "punish.gif", 0, "*PUNISH*", "*PUNISH*"
Smiley* = "wizard.gif", 0, "*WIZARD*", "*WIZARD*"
Smiley* = "victory.gif", 0, "*V*", "*V*"
Smiley* = "spiteful.gif", 0, "*SPITEFUL*", "*SPITEFUL*"
Smiley* = "tease.gif", 0, "*TEASE*", "*TEASE*"
Smiley* = "scare.gif", 0, "*SCARE*", "*SCARE*"
Smiley* = "this.gif", 0, "*THIS*", "*THIS*"
Smiley* = "paint2.gif", 0, "*PAINT*", "*PAINT*"
Smiley* = "training1.gif", 0, "*TRAINING*", "*TRAINING*"
Smiley* = "party2.gif", 0, "*PARTY*", "*PARTY*"
Smiley* = "preved.gif", 0, "*HELLO* *PREVED* *PRIVET*", "*HELLO*"
Smiley* = "mail1.gif", 0, "*WRITE* *MAIL*", "*WRITE*"
Smiley* = "dash1.gif", 0, "*WALL* *DASH*", "*WALL*"
Smiley* = "vampire.gif", 0, "*VAMPIRE* *BAT* >:-E >:E >:-e >:e" , "*VAMPIRE*"
Smiley* = "gamer4.gif", 0, "*GAMER*", "*GAMER*"
Smiley* = "popcorm1.gif", 0, "*POPCORN*", "*POPCORN*"
Smiley* = "ireful1.gif", 0, "*IREFUL*", "*IREFUL*"
;------------------------------------------
;               Custom CODE END
;------------------------------------------